name: buildAndPush
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
      acr_login_server: todoaksacrspsingh.azurecr.io
      image_name: todo-add-service
      image_version: v1
jobs:
  buildAndPush:
    name: build and push to acr
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0      
      - name: image build
        run: docker build -t $image_name:$image_version .
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: "bb540dfb-476d-42f3-bc09-65d03f6ea924"
          tenant-id: "5d1f5558-c771-40e9-a1f2-57920ed020d2"
          subscription-id: "e5efa2cd-02a5-4c7b-be99-6e2ae6d5feac"
      - name: acr login
        run: az acr login --name todoaksacrspsingh
      - name: tag to acr
        run: docker tag $image_name:$image_version $todoaksacrspsingh.azurecr.io/$image_name:$image_version        
      - name: push to acr
        run: docker push $todoaksacrspsingh.azurecr.io/$image_name:$image_version
